color0 #554248
color1 #ffb4ab
color2 #ffb0cc
color3 #f6b4cb
color4 #ffb695
color5 #ffb0cc
color6 #f6b4cb
color7 #f1dee2
color8 #a28b91
color9 #ffb4ab
color10 #ffb0cc
color11 #f6b4cb
color12 #ffb695
color13 #ffb0cc
color14 #f6b4cb
color15 #f1dee2

cursor                #f1dee2
cursor_text_color     #1a1114
background            #1a1114
foreground            #f1dee2
selection_foreground  #dac0c7
selection_background  #554248
active_border_color   #ffb0cc
inactive_border_color #554248
url_color             #ffb0cc

active_tab_foreground   #640038
active_tab_background   #ffb0cc
inactive_tab_foreground #dac0c7
inactive_tab_background #554248
cursor_trail_color      #dac0c7
