cursor            #ffb3ae
cursor_text_color #571e1c

foreground            #f1dedd
background            #140c0b
selection_foreground  #442927
selection_background  #e7bdb9
url_color             #e7bdb9

#: black 000000 767676
color0  #1a1111
color8  #3d3231
#: red cc0403 f2201f
color1  #562e3e
color9  #b06d88
#: green 19cb00 23fd00
color2  #e7bdb9
color10 #ffdad7
#: yellow cecb00 fffd00
color3  #e2c28c
color11 #ffdea6
#: blue 0d73cc 1a8fff
color4  #733330
color12 #ffb3ae
#: magenta cb1ed1 fd28ff
color5  #5d3f3d
color13 #e7bdb9
#: cyan 0dcdcd 14ffff
color6  #594319
color14 #e2c28c
#: white dddddd ffffff
color7  #d8c2bf
color15 #f1dedd

mark1_foreground #3b0809
mark1_background #ffdad7
mark2_foreground #2c1514
mark2_background #ffdad7
mark3_foreground #271900
mark3_background #ffdea6

active_tab_foreground #571e1c
active_tab_background #ffb3ae
inactive_tab_foreground #ffdad7
inactive_tab_background #733330

active_border_color #ffb3ae
inactive_border_color #571e1c
# bell_border_color #ff5a00
