foreground            #e4e1e9
background            #131318
selection_foreground  #e2e0f9
selection_background  #454559
url_color             #c0c1ff
cursor                #e4e1e9
cursor_text_color     #131318

# Tabs
active_tab_foreground   #e1e0ff
active_tab_background   #3f4178
inactive_tab_foreground #c7c5d0
inactive_tab_background #1b1b21

# Windows
active_border_color     #c0c1ff
inactive_border_color   #918f9a

# Terminal Colors (0-15)
color0  #131318
color8  #39383f

color1  #ffb4ab
color9  #93000a

color2  #c0c1ff
color10 #3f4178

color3  #c5c4dd
color11 #454559

color4  #e8b9d4
color12 #5f3c52

color5  #575992
color13 #575992

color6  #918f9a
color14 #46464f

color7  #e4e1e9
color15 #c7c5d0
