config_version = 14

[backdrop]
blur_intensity = 0.40
enabled = true
tint_intensity = 0.0

[bar.default]
center = [ "group:g3" ]
end = [ "tray", "group:g2", "group:g1" ]
margin_ends = 0
radius_top_left = 0
radius_top_right = 0
scale = 1.1
start = [ "workspaces", "group:g4", "notifications", "clipboard" ]
thickness = 35
widget_spacing = 18

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
border_width = 1
enabled = true
fill = "surface_variant"
id = "g3"
members = [ "media", "audio_visualizer" ]
opacity = 1
padding = 6

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
border_width = 1
enabled = true
fill = "surface_variant"
id = "g4"
members = [ "ram", "cpu", "temp" ]
opacity = 1
padding = 6

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
border_width = 1
enabled = true
fill = "surface_variant"
id = "g1"
members = [ "bluetooth", "network", "clock" ]
opacity = 1
padding = 6

[[bar.default.capsule_group]]
accordion = false
accordion_direction = "end"
border_width = 1
enabled = true
fill = "surface_variant"
id = "g2"
members = [ "brightness", "battery", "volume" ]
opacity = 1
padding = 6

[brightness]
enable_ddcutil = true

[hooks]
wallpaper_changed = "nautilus -q"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 600.0

[idle.behavior.lock-and-suspend]
action = "lock_and_suspend"
enabled = false
timeout = 900.0

[idle.behavior.screen-off]
action = "screen_off"
enabled = true
timeout = 660.0

[location]
auto_locate = true

[lockscreen]
transition_duration = 500

[osd.kinds]
media = false

[shell]
avatar_path = "~/Pictures/pfps/2b8daae114b9548270e25b1c15ac470b.webp"
font_family = "Inter"
launch_apps_as_systemd_services = true
screen_time_enabled = true
show_location = false

[shell.screenshot]
directory = "~/Pictures/screenshots"
show_cursor = true

[theme]
builtin = "Noctalia"
community_palette = "ADW"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

[theme.templates]
builtin_ids = [ "gtk3", "gtk4", "helix", "kitty", "starship" ]
enable_community_templates = false

[wallpaper]
directory = "~/Pictures/wallpapers"

[wallpaper.automation]
enabled = true

[wallpaper.default]
path = "~/Pictures/wallpapers/wallpaper_01.jpg"

[wallpaper.last]
path = "~/Pictures/wallpapers/wallpaper_01.jpg"

[wallpaper.monitors.DP-1]
path = "~/Pictures/wallpapers/wallpaper_01.jpg"

[widget.workspaces]
active_pill_size = 2.5
scale = 1.25
show_labels = false
